[package]
name = "cli"
version = "0.1.17"
edition = "2021"

[dependencies]
clap.workspace = true
kern.workspace = true
network.workspace = true
bincode.workspace = true

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
strip = true