[package]
name = "kern"
version = "0.1.0"
edition = "2021"

[lib]
crate-type=["rlib", "cdylib"]

[dependencies]
bincode.workspace = true
sha3.workspace = true
toml.workspace = true
serde.workspace = true
miniz_oxide.workspace = true
indextree.workspace = true
