[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cc="*"

[dependencies]
indextree = "4.7.2"
tree-sitter = "0.23.0"
tree-sitter-c = "0.23.0"
core = { path = "../core"}