[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cc.workspace = true

[dependencies]
indextree.workspace = true
regex.workspace = true
tree-sitter.workspace = true
tree-sitter-c.workspace = true
kern.workspace = true