[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cc="*"

[dependencies]
indextree = "4.7.2"
regex = "1.10.6"
tree-sitter = "0.23.0"
tree-sitter-c = "0.23.0"
kern = { path = "../kern"}