[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version="4.5.16", features = [ "derive" ] }
bincode = "2.0.0-rc.3"
network = { path = "../network" }
kern = { path = "../kern" }